[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # vim上でgitコマンド
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = '0'
rev = 'release'
hook_add = '''
let g:coc_global_extensions = ['coc-solargraph']
'''

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <silent> ,f :GFiles<CR>
nnoremap <silent> ,F :GFiles?<CR>
nnoremap <silent> ,b :Buffers<CR>
nnoremap <silent> ,l :BLines<CR>
nnoremap <silent> ,h :History<CR>
nnoremap <silent> ,m :Mark<CR>

" 上部表示
let g:fzf_layout = { 'up': '~40%' }
" 新規タブ
let g:fzf_layout = { 'window': '-tabnew' }
'''
