# [[plugins]]
# repo = 'vim-syntastic/syntastic'
# hook_add = '''
# set statusline+=%#warningmsg#
# set statusline+=%{SyntasticStatuslineFlag()}
# set statusline+=%*
# 
# let g:syntastic_always_populate_loc_list = 0
# let g:syntastic_auto_loc_list = 0
# let g:syntastic_check_on_open = 1
# let g:syntastic_check_on_wq = 0
# 
# let g:syntastic_mode_map = { 'mode': 'active', 'active_filetypes': [
#   \ 'ruby', 'javascript','coffee', 'scss', 'html', 'haml', 'slim', 'sh',
#   \ 'spec', 'vim', 'zsh', 'sass', 'eruby'] }
# 
# let g:syntastic_javascript_checkers=['eslint']
# let g:syntastic_coffee_checkers = ['coffeelint']
# let g:syntastic_scss_checkers = ['scss_lint']
# let g:syntastic_ruby_checkers = ['rubocop']
# 
# let g:syntastic_error_symbol='✗'
# let g:syntastic_style_error_symbol = '✗'
# let g:syntastic_warning_symbol = '⚠'
# let g:syntastic_style_warning_symbol = '⚠'
# '''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'md'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js','javascript']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'jbuilder', 'pryrc']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
